### ISSUE TITLE
Integrate Keycloak for signup/user-creation process

### ISSUE THREAD

**Issue by acyuta1** [dhanush1909/rafantasy#14]
Figure out how to create users using keycloak api's and use those in our application.

COA's:

- Decide whether to store users both in keycloak server as well as postgres db.
- Regardless of COA i., implement signup in AuthController.java with proper payload 
- On successful validation, the user must be saved in keycloak server's **users** section correctly in the correct **Realm**, with proper **Role**.

**Comment by dhanush1909** [comment]
not needed since signup/signin is done in frontend
